/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sakila;

import java.util.Date;
import java.util.Iterator;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.hibernate.cfg.Configuration;
import org.hibernate.service.ServiceRegistry;
import org.hibernate.Transaction;


public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        filmsByLanguage();
    }

    public static void country(){
        Session session;

        Configuration configuration = new Configuration().configure();

        // IMPORTANT : On Ajoute bien nos Entités !!
        configuration.addAnnotatedClass(Country.class);
        // Fin Ajout entités

        SessionFactory sessionFactory = configuration.buildSessionFactory();
        session = sessionFactory.openSession();

        Country a1 = session.getReference(Country.class, 34);

        System.out.println(a1.getCountry());
        session.close();


    }

    public static void bases(){
        Session session;

        Configuration configuration = new Configuration().configure();

        SessionFactory sessionFactory = configuration.buildSessionFactory();
        session = sessionFactory.openSession();

        Actor a1 = session.getReference(Actor.class, 2);

        System.out.println(a1.getFirstName());
        session.close();
    }


    public static void film(){
        Session session;

        Configuration configuration = new Configuration().configure("/hibernate.cfg.xml");

        // IMPORTANT : On Ajoute bien nos Entités !!
        configuration.addAnnotatedClass(Film.class);
        configuration.addAnnotatedClass(Language.class);

        // IMPORTANT
        ServiceRegistry serviceRegistry = new StandardServiceRegistryBuilder().applySettings(configuration.getProperties()).build();
        SessionFactory sessionFactory = configuration.buildSessionFactory(serviceRegistry);
        session = sessionFactory.openSession();

        Film a1 = session.getReference(Film.class, 3);

        System.out.println(a1.getTitle());  
        session.close();
    }

    public static void addFilmLanguage(){
        Configuration configuration = new Configuration().configure();

        SessionFactory sessionFactory = configuration.buildSessionFactory();
        Session session = sessionFactory.openSession();

        Language l = new Language();
        l.setName("Martien");
        l.setLastUpdate(new Date());
        Film f = new Film();
        f.setDescription("C'est un film martien");
        f.setTitle("Mars attack !");
        f.setReleaseYear(1996);
        f.setLanguage(l);
        f.setRentalDuration(6);
        f.setRentalRate(0.5f);
        f.setRating("PG");
        f.setSpecialFeatures("Deleted Scenes");
        f.setReplacementCost(22f);
        f.setLastUpdate(new Date());
        Transaction tx = session.beginTransaction();
        session.persist(l);
        session.persist(f);
        tx.commit();
        
    }

    public static void filmsByLanguage(){
        Configuration configuration = new Configuration().configure();

        SessionFactory sessionFactory = configuration.buildSessionFactory();
        Session session = sessionFactory.openSession();

        Language l = session.getReference(Language.class, 1);
        
        System.out.println(l.getName());
        
        Iterator<Film> i = l.getFilmsParLangue().iterator(); 

        while(i.hasNext()){
            System.out.println(i.next().getTitle());
        }
        
    }
}
