/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sakila;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;

class HibernateTest {

    @Test void TestsHibernate() {
        // Création d'une connexion vers notre SGBD
        Configuration configuration = new Configuration().configure();
        SessionFactory sessionFactory = configuration.buildSessionFactory();
        Session session = sessionFactory.openSession();
        assertNotNull(session);
    }
}
